// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyrjwcuwbuqkwccvdfst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5cmp3Y3V3YnVxa3djY3ZkZnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNzMxMjEsImV4cCI6MjA4Mzg0OTEyMX0.tnconebFw-ehvgZNJZG_ZrLJls5bGaoefFmW0j4aQQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});